# Generated by Django 4.2 on 2023-09-25 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_movieinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='cast',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='download_url',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='genres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='release_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='screenshots',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='source_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='source_url',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='movieinfo',
            name='trailer_url',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
